name: eshop
description: A flutter exercise project that perform e-commerce UI and design flow with local json data.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # getX
  get: 4.6.1

  # notification badge
  badges: ^2.0.2

  # Icons for app
  font_awesome_flutter: ^10.1.0

  # scala fold
  dartz: ^0.10.0

  carousel_slider: ^4.0.0

  flutter_shine: ^0.0.5

  cached_network_image: ^3.2.0

  slide_countdown_clock: ^1.0.3

  flutter_linkify: ^5.0.2

  switcher_button: ^0.0.4

  cart_stepper: ^2.0.2

  flutter_launcher_icons: ^0.9.2

  get_storage: ^2.0.3

  intl: ^0.17.0

  flutter_barcode_scanner: ^2.0.0

  google_fonts: ^2.3.1

  animated_text_kit: ^4.2.1

  http: ^0.13.4

  html: ^0.15.0

  simple_animations: ^4.0.1

  animated_splash_screen: ^1.2.0

  liquid_swipe: ^2.1.1

  url_launcher: ^6.1.2

  flutter_onboarding_screen:


dev_dependencies:
  flutter_test:
    sdk: flutter

  get_test: 4.0.1
  network_image_mock: ^2.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sample/sampleProduct.json
    - assets/sample/homeData.json
    - assets/sample/notificationData.json
    - assets/sample/
    - assets/images/
    - assets/icon/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
